### ISSUE TITLE
Badges Seem Broken

### ISSUE THREAD

**Issue by akshaaatt** [pavi2410/PlayBadges#8]
- A question mark is shown rather than the badge for all repositories including yours.

**Comment by pavi2410** [comment]
Yeah, right... Looks like the `google-play-scraper` lib is broken.

```
GET /badge/downloads?id=appinventor.ai_pavitragolchha.VR&pretty 404 228.500 ms - 9
TypeError: Cannot read property 'replace' of undefined
    at Object.descriptionText [as fun] (/home/runner/PlayBadges/node_modules/google-play-scraper/lib/mappers/details.js:104:51)
    at /home/runner/PlayBadges/node_modules/google-play-scraper/lib/utils/scriptData.js:52:19
    at XWrap.f (/home/runner/PlayBadges/node_modules/ramda/dist/ramda.js:5955:28)
    at XWrap.@@transducer/step (/home/runner/PlayBadges/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (/home/runner/PlayBadges/node_modules/ramda/dist/ramda.js:5137:46)
    at _reduce (/home/runner/PlayBadges/node_modules/ramda/dist/ramda.js:5167:24)
    at map (/home/runner/PlayBadges/node_modules/ramda/dist/ramda.js:5954:20)
    at /home/runner/PlayBadges/node_modules/ramda/dist/ramda.js:586:23
    at Object.f2 [as map] (/home/runner/PlayBadges/node_modules/ramda/dist/ramda.js:473:22)
    at extractFields (/home/runner/PlayBadges/node_modules/google-play-scraper/lib/utils/scriptData.js:40:14)
```

**Comment by akshaaatt** [comment]
Great. Thanks!

**Comment by akshaaatt** [comment]
Need to reopen this.

**Comment by pavi2410** [comment]
It should be working again now

**Comment by akshaaatt** [comment]
Thanks!
